-- Avena PostgreSQL schema v8
CREATE TABLE IF NOT EXISTS "Genre" ("ID" SERIAL PRIMARY KEY, "NameGenre" TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "User" ("ID" SERIAL PRIMARY KEY, "Username" TEXT NOT NULL UNIQUE, "Name" TEXT NOT NULL, "Password" TEXT NOT NULL, "AvatarImg" TEXT NOT NULL DEFAULT '');
CREATE UNIQUE INDEX IF NOT EXISTS "UX_User_Username_Lower" ON "User" (LOWER("Username"));
CREATE TABLE IF NOT EXISTS "Author" ("ID" SERIAL PRIMARY KEY, "FullName" TEXT NOT NULL, "Role" TEXT, "Affiliation" TEXT, "Location" TEXT);
CREATE TABLE IF NOT EXISTS "News" ("ID" SERIAL PRIMARY KEY, "Title" TEXT NOT NULL, "Info" TEXT NOT NULL, "Image" TEXT, "Views" INTEGER NOT NULL DEFAULT 0, "CountOfLikes" INTEGER NOT NULL DEFAULT 0, "GenreID" INTEGER NOT NULL REFERENCES "Genre"("ID"), "AuthorID" INTEGER NULL REFERENCES "Author"("ID") ON DELETE SET NULL, "DateOfPost" TIMESTAMP NOT NULL DEFAULT NOW(), "DeletedAt" TIMESTAMP);
CREATE TABLE IF NOT EXISTS "Comment" ("ID" SERIAL PRIMARY KEY, "NewsID" INTEGER NOT NULL REFERENCES "News"("ID"), "UserID" INTEGER NOT NULL REFERENCES "User"("ID"), "Text" TEXT NOT NULL, "CountOfLikes" INTEGER NOT NULL DEFAULT 0, "DateOfPost" TIMESTAMP NOT NULL DEFAULT NOW());
